Repository likelion-backend-2nd-project-team11/book-more, pull requests merged in 2023-01, with the labels that each got.

#15 [Hotfix] 시큐리티 설정 변경
  backend/src/main/java/site/bookmore/bookmore/security/config/WebSecurityConfig.java
Labels: review

#16 카카오 도서 검색 api 연동
  backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/KakaoBookSearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/dto/Document.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/dto/KakaoSearchParams.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/dto/KakaoSearchResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/dto/Meta.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/BookControllerTest.java
Labels: review

#20 알람 이벤트 핸들러 구현
  backend/src/main/java/site/bookmore/bookmore/alarms/controller/AlarmController.java
  backend/src/main/java/site/bookmore/bookmore/alarms/entity/Alarm.java
  backend/src/main/java/site/bookmore/bookmore/alarms/entity/AlarmType.java
  backend/src/main/java/site/bookmore/bookmore/alarms/entity/dto/AlarmResponse.java
  backend/src/main/java/site/bookmore/bookmore/alarms/repository/AlarmRepository.java
  backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
  backend/src/main/java/site/bookmore/bookmore/observer/event/alarm/AlarmCreate.java
  backend/src/main/java/site/bookmore/bookmore/observer/handler/AlarmEventHandler.java
  backend/src/main/java/site/bookmore/bookmore/security/config/AsyncConfig.java
  backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
Labels: review

#21 팔로우/팔로잉 기능 구현
  backend/src/main/java/site/bookmore/bookmore/common/entity/BaseEntity.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/bad_request/FollowNotMeException.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/not_found/FollowNotFoundException.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/FollowController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/Follow.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/FollowRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/FollowControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/users/service/FollowServiceTest.java
Labels: review

#22 회원가입 /로그인
  backend/build.gradle
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/badrequest/BadConstantException.java
  backend/src/main/java/site/bookmore/bookmore/security/config/PasswordEncoderConfig.java
  backend/src/main/java/site/bookmore/bookmore/security/config/WebSecurityConfig.java
  backend/src/main/java/site/bookmore/bookmore/security/fiter/JwtAuthenticationFilter.java
  backend/src/main/java/site/bookmore/bookmore/security/provider/JwtProvider.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserJoinRequest.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserJoinResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserLoginRequest.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserLoginResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/Role.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/User.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
Labels: review

#23 도서 리뷰 등록 / 좋아요 | 취소
  backend/src/main/java/site/bookmore/bookmore/books/controller/ReviewController.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Likes.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/LikesRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/ReviewControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
Labels: review

#24 챌린지 기능 구현
  backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeDetailResponse.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeListResponse.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeResponse.java
  backend/src/main/java/site/bookmore/bookmore/challenge/entity/Challenge.java
  backend/src/main/java/site/bookmore/bookmore/challenge/repository/ChallengeRepository.java
  backend/src/main/java/site/bookmore/bookmore/challenge/service/ChallengeService.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/not_found/UserNotFoundException.java
  backend/src/test/java/site/bookmore/bookmore/challenge/controller/ChallengeControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/challenge/service/ChallengeServiceTest.java
Labels: review

#26 GlobalExceptionHandler 구현
  backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
Labels: review

#29 배포 전 수정
  backend/src/main/java/site/bookmore/bookmore/alarms/entity/dto/AlarmResponse.java
  backend/src/main/java/site/bookmore/bookmore/alarms/repository/AlarmRepository.java
  backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/BookResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Author.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Likes.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Translator.java
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeDetailResponse.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
  backend/src/main/java/site/bookmore/bookmore/challenge/entity/Challenge.java
  backend/src/main/java/site/bookmore/bookmore/challenge/service/ChallengeService.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/bad_request/BadConstantException.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/Role.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/FollowRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
  backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/challenge/controller/ChallengeControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/challenge/service/ChallengeServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/users/service/FollowServiceTest.java
Labels: review

#35 팔로우 기능 수정
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/conflict/DuplicateFollowException.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/conflict/DuplicateUnfollowException.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/FollowController.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/FollowRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
Labels: review

#43 도서 리뷰: review & chart로 DB 테이블 분리
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Chart.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/ReviewControllerTest.java
Labels: review

#38 리뷰 등록 알림 기능 추가
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/FollowRepository.java
  backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
Labels: review

#40 팔로우 알람 기능 구현
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
Labels: review

#45 팔로우 기능/테스트 코드 수정
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/conflict/DuplicateUnfollowException.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
  backend/src/test/java/site/bookmore/bookmore/users/service/FollowServiceTest.java
Labels: review

#48 [Feat] home, header
  frontend/css/header.css
  frontend/css/home.css
  frontend/html/header.html
  frontend/html/home.html
  frontend/js/header.js
  frontend/js/home.js
Labels: review

#49 도서 리뷰 조회 기능
  backend/src/main/java/site/bookmore/bookmore/books/controller/ReviewController.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewPageResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/ReviewControllerTest.java
Labels: review

#51 회원 정보 수정/ 회원 탈퇴 기능
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserUpdateRequest.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/User.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/UserRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
Labels: review

#52 도서 상세 조회 구현
  backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/BookResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Author.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Subject.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Translator.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/BookRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/service/BookService.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/KakaoBookSearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/dto/Document.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kolis/KolisBookSearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kolis/dto/Doc.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kolis/dto/KolisSearchParams.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kolis/dto/KolisSearchResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/util/mapper/BookMapper.java
  backend/src/main/java/site/bookmore/bookmore/books/util/mapper/BookResponseMapper.java
Labels: review

#65 도서 검색 기능 리팩토링
  backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
  backend/src/main/java/site/bookmore/bookmore/books/service/BookService.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/BookSearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/KakaoBookSearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kolis/KolisBookSearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kolis/dto/Doc.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kolis/dto/KolisSearchResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/util/mapper/BookMapper.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/BookControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/BookServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/books/util/api/kolis/dto/DocTest.java
Labels: review

#60 도서 리뷰 수정/삭제 기능 구현
  backend/src/main/java/site/bookmore/bookmore/books/controller/ReviewController.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewPageResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Chart.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/ReviewControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
Labels: review

#78 Create [2주차]idea_11팀_진행상황_공유.md
  Weekly_Log/[2주차]idea_11팀_진행상황_공유.md
Labels: done

#66 이메일 형식 로직 추가
  backend/src/main/java/site/bookmore/bookmore/common/dto/ResultResponse.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserJoinRequest.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserLoginRequest.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
Labels: review

#69 도서 검색 페이지 디자인
  frontend/css/books.css
  frontend/css/index.css
  frontend/css/nav.css
  frontend/html/book.html
  frontend/html/books.html
  frontend/html/index.html
  frontend/js/bookSearch.js
Labels: review

#75 상단바 프런트
  frontend/css/top-bar.css
  frontend/fonts/BMHANNAAir_otf.otf
  frontend/fonts/BMHANNAAir_ttf.ttf
  frontend/html/top-bar.html
Labels: review

#79 리뷰 삭제 체크 수정
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
Labels: bug

#81 Jacoco 설정 및 github actions workflow 수정
  .github/workflows/develop.yml
  .github/workflows/main.yml
  backend/build.gradle
  backend/lombok.config
Labels: review

#99 FrontEnd CI PipeLine 작성
  .github/workflows/front.yml
Labels: review

#90 Detail 페이지 작성
  frontend/css/detail.css
  frontend/detail.html
Labels: review

#92 로그인 회원가입 프론트 구현
  frontend/css/join-login.css
  frontend/join.html
  frontend/js/join.js
  frontend/js/login.js
  frontend/login.html
Labels: review

#94 도서 검색, 상세조회 페이지 수정
  frontend/book.html
  frontend/books.html
  frontend/css/index.css
  frontend/css/nav.css
  frontend/index.html
  frontend/js/bookSearch.js
  frontend/top-bar.html
Labels: review

#106 workflow 수정
  .github/workflows/develop.yml
  .github/workflows/front.yml
  .github/workflows/main.yml
Labels: review

#104 [update] controller, request, repository, service
  backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
  backend/src/main/java/site/bookmore/bookmore/challenge/entity/Challenge.java
  backend/src/main/java/site/bookmore/bookmore/challenge/repository/ChallengeRepository.java
  backend/src/main/java/site/bookmore/bookmore/challenge/service/ChallengeService.java
Labels: review

#87 [Hotfix] 도서 상세조회 번역가가 없는 경우 DB에러 이슈 해결
  backend/src/main/java/site/bookmore/bookmore/books/repository/BookRepository.java
Labels: review

#88 Feature/#42 랭킹 조회,스케줄러 적용
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
  backend/src/main/java/site/bookmore/bookmore/config/ScheduleConfig.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/RanksController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/RanksResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/Ranks.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/RanksRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/UserRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/service/RanksService.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/main/java/site/bookmore/bookmore/users/vo/RanksNativeVo.java
  backend/src/main/resources/application.properties
  backend/src/test/java/site/bookmore/bookmore/users/controller/RanksControllerTest.java
Labels: review

#96 Swagger 설정
  backend/build.gradle
  backend/src/main/java/site/bookmore/bookmore/alarms/controller/AlarmController.java
  backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
  backend/src/main/java/site/bookmore/bookmore/books/controller/ReviewController.java
  backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
  backend/src/main/java/site/bookmore/bookmore/common/dto/Paging.java
  backend/src/main/java/site/bookmore/bookmore/common/support/annotation/Authorized.java
  backend/src/main/java/site/bookmore/bookmore/config/SwaggerConfig.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/FollowController.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
Labels: review

#100 네이버 api 추가 및 도서 검색 리팩터링
  backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/BookDetailResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/BookResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/BookSearchParams.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
  backend/src/main/java/site/bookmore/bookmore/books/service/BookService.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/NaverBooksearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/dto/Item.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/dto/NaverSearchParams.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/dto/NaverSearchResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/util/mapper/BookMapper.java
  backend/src/main/java/site/bookmore/bookmore/books/util/mapper/BookResponseMapper.java
  backend/src/main/java/site/bookmore/bookmore/common/dto/ResultResponse.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/BookControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/BookServiceTest.java
Labels: review
