Repository likelion-backend-2nd-project-team11/book-more, pull requests merged in 2023-02, with the labels that each got.

#118 도서 리뷰 작성
  frontend/books/review.html
  frontend/css/review.css
  frontend/js/review.js
Labels: review

#121 마이 피드 페이지 수정
  frontend/asset/default-profile.png
  frontend/books/detail.html
  frontend/books/search.html
  frontend/challenge/index.html
  frontend/index.html
  frontend/js/review.js
  frontend/users/detail.html
Labels: review

#122 팔로잉/팔로워 카운트 기능 추가
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/FollowCount.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/User.java
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
Labels: review

#123 Feature/#42 ranks 테이블에 nickname 추가
  backend/src/main/java/site/bookmore/bookmore/users/dto/RanksResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/Ranks.java
  backend/src/main/java/site/bookmore/bookmore/users/service/RanksService.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/main/java/site/bookmore/bookmore/users/vo/RanksNativeVo.java
Labels: review

#124 [feat] mypage.html/css
  frontend/css/mypage.css
  frontend/mypage.html
Labels: review

#127 유저 상세 조회 추가
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserDetailResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
Labels: review

#132 알림 페이지 구현(디자인)
  frontend/notifications/notifications.html
Labels: done

#136 Feature/#133 ranks 페이지
  frontend/css/detail.css
  frontend/ranks.html
Labels: review

#135 Feature/#42 nickname 추가
  backend/src/main/java/site/bookmore/bookmore/users/entity/Ranks.java
  backend/src/main/java/site/bookmore/bookmore/users/vo/RanksNativeVo.java
Labels: review

#142 OAuth2 google 적용
  backend/build.gradle
  backend/src/main/java/site/bookmore/bookmore/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/site/bookmore/bookmore/oauth2/OAuth2Attribute.java
  backend/src/main/java/site/bookmore/bookmore/oauth2/OAuth2SuccessHandler.java
  backend/src/main/java/site/bookmore/bookmore/oauth2/util/mapper/UserMapper.java
  backend/src/main/java/site/bookmore/bookmore/security/config/WebSecurityConfig.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/User.java
  backend/src/main/resources/application.properties
  backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/challenge/controller/ChallengeControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/FollowControllerTest.java
  backend/src/test/resources/application.properties
Labels: review

#143 Feature/#138 팔로잉이 리뷰를 등록했을 때의 알림 로직 변경
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/main/java/site/bookmore/bookmore/observer/event/alarm/AlarmListCreate.java
  backend/src/main/java/site/bookmore/bookmore/observer/handler/AlarmEventHandler.java
Labels: review

#144 #125
  backend/build.gradle
  backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
  backend/src/test/java/site/bookmore/bookmore/challenge/controller/ChallengeControllerTest.java
Labels: review

#140 도서 리뷰 작성 Validation 적용
  backend/src/main/java/site/bookmore/bookmore/books/controller/ReviewController.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ChartRequest.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/common/dto/ErrorResponse.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/ReviewControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
Labels: review

#146 Weekly_Log 3주차
  Weekly_Log/[3주차]idea_11팀_진행상황_공유.md
Labels: review

#149 Update README.md
  README.md
Labels: review

#152 유저 id로 리뷰 조회
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
Labels: review

#154 프로필 사진 등록 기능 구현(AWS S3)
  backend/build.gradle
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/bad_request/FileNotExistsException.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/conflict/DuplicateProfileException.java
  backend/src/main/java/site/bookmore/bookmore/s3/AwsS3Uploader.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserProfileResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/User.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
Labels: review

#155 #145
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserUpdateResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
Labels: review

#159 태그 기능 구현
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewPageResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/books/dto/TagResponse.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/ReviewTag.java
  backend/src/main/java/site/bookmore/bookmore/books/entity/Tag.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewTagRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/repository/TagRepository.java
  backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/not_found/ReviewTagRelationNotFound.java
  backend/src/test/java/site/bookmore/bookmore/books/controller/ReviewControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
Labels: review

#162 [update] 스포일러 더보기 처리
  frontend/js/review.js
Labels: review

#172 [Feat] 크롤링 추가
  backend/build.gradle
  backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/NaverBookCrawler.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/NaverBooksearch.java
Labels: review

#177 AlarmResponse 수정
  backend/src/main/java/site/bookmore/bookmore/alarms/dto/AlarmResponse.java
  backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
  backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
Labels: review

#179 AlarmResponse 수정 및 새로운 알림만 조회하는 기능 추가
  backend/src/main/java/site/bookmore/bookmore/alarms/controller/AlarmController.java
  backend/src/main/java/site/bookmore/bookmore/alarms/entity/Alarm.java
  backend/src/main/java/site/bookmore/bookmore/alarms/repository/AlarmRepository.java
  backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/conflict/DuplicateConfirmedException.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/not_found/AlarmNotFoundException.java
  backend/src/main/java/site/bookmore/bookmore/reviews/service/ReviewService.java
Labels: review

#178 개인 랭킹 구현
  backend/src/main/java/site/bookmore/bookmore/users/controller/RanksController.java
  backend/src/main/java/site/bookmore/bookmore/users/service/RanksService.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/RanksControllerTest.java
Labels: review

#180 회원탈퇴 비즈니스 로직 수정
  backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
  backend/src/main/java/site/bookmore/bookmore/challenge/repository/ChallengeRepository.java
  backend/src/main/java/site/bookmore/bookmore/challenge/service/ChallengeService.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/not_found/AlreadyDeletedUserException.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/not_found/RanksNotFoundException.java
  backend/src/main/java/site/bookmore/bookmore/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/site/bookmore/bookmore/reviews/service/ReviewService.java
  backend/src/main/java/site/bookmore/bookmore/security/config/WebSecurityConfig.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/Ranks.java
  backend/src/main/java/site/bookmore/bookmore/users/entity/User.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/FollowRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/RanksRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/repositroy/UserRepository.java
  backend/src/main/java/site/bookmore/bookmore/users/scheduler/RanksScheduler.java
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/test/java/site/bookmore/bookmore/challenge/service/ChallengeServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/reviews/service/ReviewServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/users/service/FollowServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
Labels: review

#181 팔로우/팔로잉/유저 조회 수정
  backend/src/main/java/site/bookmore/bookmore/reviews/dto/ReviewPageResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/FollowController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserDetailResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserPersonalResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
Labels: review

#183 도서 상세조회, 회원가입 페이지 수정 및 favicon 추가
  frontend/asset/android-icon-144x144.png
  frontend/asset/android-icon-192x192.png
  frontend/asset/android-icon-36x36.png
  frontend/asset/android-icon-48x48.png
  frontend/asset/android-icon-72x72.png
  frontend/asset/android-icon-96x96.png
  frontend/asset/apple-icon-114x114.png
  frontend/asset/apple-icon-120x120.png
  frontend/asset/apple-icon-144x144.png
  frontend/asset/apple-icon-152x152.png
  frontend/asset/apple-icon-180x180.png
  frontend/asset/apple-icon-57x57.png
  frontend/asset/apple-icon-60x60.png
  frontend/asset/apple-icon-72x72.png
  frontend/asset/apple-icon-76x76.png
  frontend/asset/apple-icon-precomposed.png
  frontend/asset/apple-icon.png
  frontend/asset/browserconfig.xml
  frontend/asset/favicon-16x16.png
  frontend/asset/favicon-32x32.png
  frontend/asset/favicon-96x96.png
  frontend/asset/favicon.ico
  frontend/asset/manifest.json
  frontend/asset/ms-icon-144x144.png
  frontend/asset/ms-icon-150x150.png
  frontend/asset/ms-icon-310x310.png
  frontend/asset/ms-icon-70x70.png
  frontend/books/detail.html
  frontend/books/review.html
  frontend/books/search.html
  frontend/challenge/index.html
  frontend/index.html
  frontend/js/book.js
  frontend/js/join.js
  frontend/notifications/index.html
  frontend/oauth2/redirect.html
  frontend/ranks.html
  frontend/users/detail.html
  frontend/users/join.html
  frontend/users/login.html
  frontend/users/mypage.html
Labels: review

#185 알림 페이지 js & html
  frontend/books/detail.html
  frontend/books/review.html
  frontend/books/search.html
  frontend/challenge/index.html
  frontend/index.html
  frontend/js/notifications.js
  frontend/notifications/index.html
  frontend/ranks.html
  frontend/top-bar.html
  frontend/users/detail.html
  frontend/users/join.html
  frontend/users/login.html
  frontend/users/mypage.html
Labels: review

#187 마이페이지
  frontend/js/mypage.js
  frontend/users/join.html
  frontend/users/mypage.html
Labels: review

#198 알림 dto & js 스크립트 수정
  backend/src/main/java/site/bookmore/bookmore/alarms/dto/AlarmResponse.java
  backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
  frontend/index.html
  frontend/js/notifications.js
Labels: review

#200 ReviewPageResponse에 유저 id 추가
  backend/src/main/java/site/bookmore/bookmore/reviews/dto/ReviewPageResponse.java
Labels: review

#203 스포일러 더보기, 숨기기 버튼 오동작, 태그 파싱 로직 수정
  frontend/js/login.js
  frontend/js/review.js
Labels: review

#204 랭킹 js 스크립트 수정
  frontend/js/ranks.js
  frontend/ranks.html
Labels: review

#206 [bug] 비밀번호 이슈
  frontend/js/mypage.js
Labels: review

#207 태그 수정, 탈퇴한 유저 로그인되는 이슈, 패스워드 수정 이슈 해결
  backend/src/main/java/site/bookmore/bookmore/reviews/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/reviews/service/ReviewService.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserUpdateRequest.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
Labels: review

#208 [update] 프로필 수정
  frontend/js/mypage.js
  frontend/users/mypage.html
Labels: review

#212 Feature/#211
  frontend/js/join.js
  frontend/users/join.html
Labels: review

#221 myfeed.js에 alert 메세지 수정
  frontend/js/myfeed.js
Labels: review

#222 테스트 코드 작성 및 불필요한 변수 삭제
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/FollowControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
  backend/src/test/java/site/bookmore/bookmore/users/service/FollowServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
Labels: review

#224 회원 탈퇴 시, 확인 팝업 필요, placeholder 변경
  frontend/js/mypage.js
  frontend/js/notifications.js
  frontend/users/join.html
Labels: review

#225 회원 탈퇴 시, 알림 처리
  backend/src/main/java/site/bookmore/bookmore/alarms/entity/Alarm.java
  backend/src/main/java/site/bookmore/bookmore/alarms/repository/AlarmRepository.java
  backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
Labels: review

#226 #213
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
  frontend/asset/google.png
  frontend/books/detail.html
  frontend/books/review.html
  frontend/books/search.html
  frontend/challenge/index.html
  frontend/index.html
  frontend/js/challenge.js
  frontend/js/deadline.js
  frontend/ranks.html
  frontend/users/detail.html
  frontend/users/join.html
  frontend/users/login.html
Labels: review

#228 소셜 로그인, 크롤러, 리뷰 컴포넌트 디자인 변경
  backend/src/main/java/site/bookmore/bookmore/books/util/api/kakao/KakaoBookSearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/NaverBookCrawler.java
  backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/NaverBooksearch.java
  backend/src/main/java/site/bookmore/bookmore/books/util/crawler/AbstractBookCrawler.java
  backend/src/main/java/site/bookmore/bookmore/books/util/crawler/BookCrawler.java
  backend/src/main/java/site/bookmore/bookmore/books/util/crawler/KakaoBookCrawler.java
  backend/src/main/java/site/bookmore/bookmore/books/util/crawler/NaverBookCrawler.java
  backend/src/main/java/site/bookmore/bookmore/config/BookCrawlerConfig.java
  backend/src/main/java/site/bookmore/bookmore/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/site/bookmore/bookmore/oauth2/Oauth2FailureHandler.java
  backend/src/main/java/site/bookmore/bookmore/security/config/WebSecurityConfig.java
  backend/src/main/resources/application.properties
  frontend/js/review.js
Labels: review

#220 프로필 사진 변경 기능 Fix
  backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
  backend/src/main/java/site/bookmore/bookmore/common/exception/unauthorized/InvalidFileFormatException.java
  backend/src/main/java/site/bookmore/bookmore/s3/AwsS3Uploader.java
  frontend/js/mypage.js
  frontend/users/mypage.html
Labels: review

#229 [4주차]idea_11팀_진행상황_공유.md
  Weekly_Log/[4주차]idea_11팀_진행상황_공유.md
Labels: review

#233 myPage 비밀번호 확인 추가
  frontend/js/mypage.js
  frontend/users/mypage.html
Labels: review

#236 챌린지 글자 수 제한 #235
  frontend/challenge/index.html
Labels: review

#238 프로필 사진 변경 기능 수정
  backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
  frontend/js/mypage.js
Labels: review

#239 컬럼 길이 수정 및 Validator 추가
  backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
  backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
  backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
  backend/src/main/java/site/bookmore/bookmore/challenge/entity/Challenge.java
  backend/src/main/java/site/bookmore/bookmore/reviews/controller/ReviewController.java
  backend/src/main/java/site/bookmore/bookmore/reviews/dto/ReviewRequest.java
  backend/src/main/java/site/bookmore/bookmore/reviews/entity/Review.java
  backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserJoinRequest.java
  backend/src/main/java/site/bookmore/bookmore/users/dto/UserUpdateRequest.java
  backend/src/test/java/site/bookmore/bookmore/books/service/BookServiceTest.java
  backend/src/test/java/site/bookmore/bookmore/challenge/controller/ChallengeControllerTest.java
  frontend/js/review.js
Labels: review

#240 [Feat] 리뷰 수정 이슈 해결
  frontend/books/detail.html
Labels: review

#241 리뷰 페이징 처리
  frontend/books/detail.html
  frontend/js/review.js
Labels: review

#242 [fix] challenge 내용 제한 300자 카운팅 추가
  frontend/challenge/index.html
Labels: review

#243 README.md 수정
  README.md
  assets/architecture.png
  assets/favicon.png
  assets/infra.png
  assets/stack1.png
  assets/stack2.png
  assets/stack3.png
Labels: inProgress

#249 [Update] README.md 최종 수정...
  README.md
Labels: review
